### ISSUE TITLE
Environment variables don't get replaced

### ISSUE THREAD

**Issue by khauser** [bery/helm-set#1]
values.yaml
```
icm:
  icm-as:
    image:
      repository: "${ICM_TEST_IMAGE}"
```

environment.sh
```
#!/usr/bin/env bash
ICM_TEST_IMAGE="whatever"
```

After executing `source ./environment.sh` and `helm install ..` the env variable are not replaced.

My base image for execution is `ubuntu-20.4-DS1_v2-adopt-adoptium-jdk` with the following RUN cmd to install helm:

```
RUN apk add --no-cache ca-certificates bash git openssh curl \
    && wget -q https://storage.googleapis.com/kubernetes-release/release/${KUBE_LATEST_VERSION}/bin/linux/amd64/kubectl -O /usr/local/bin/kubectl \
    && chmod +x /usr/local/bin/kubectl \
    && wget -q https://get.helm.sh/helm-${HELM_VERSION}-linux-amd64.tar.gz -O - | tar -xzO linux-amd64/helm > /usr/local/bin/helm \
    && chmod +x /usr/local/bin/helm
```

**Comment by bery** [comment]
Hi @khauser,

this plugin is not intended to work like this. If you have any helm value in your chart you can override the value using an env var like this

`image:
    tag: "latest"`

HELM_VAR_image__test = "not-latest"

when you execute helm install via `helm set` the `image.test` value will be passed to the helm command

`helm set install <release> <chart>` will get internally translated to `helm install <release> chart --set image.tag=...`

Hope this helps!

Lukas
